#!/bin/bash
#
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.

# create the uploads directory if it doesn't exist
echo ".............pre_build............creating symlinks................."
if [ ! -d "$OPENSHIFT_DATA_DIR/upload" ]; then
    mkdir $OPENSHIFT_DATA_DIR/upload
    echo directory made.
fi

ln -s ${OPENSHIFT_DATA_DIR}/upload ${OPENSHIFT_REPO_DIR}/php/upload
echo ".................creating symlinks completed........................"
