#!/bin/bash
#
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.

# create the uploads directory if it doesn't exist
echo ".............pre_build............creating symlinks................."
ln -s ${OPENSHIFT_DATA_DIR} ${OPENSHIFT_REPO_DIR}php/src
echo ".................creating symlinks completed........................"
